package com.deliverypp.util;

public enum DeliveryppResponseStatus {

    USER_UPDATED, USER_EMAIL_TAKEN, USER_NOT_FOUND, USER_INVALID_ROLE, USER_NAME_TAKEN, USER_INVALID_CRED,
    ORDER_NOT_FOUND, ORDER_NOT_SAVED, ORDER_INVALID,
    ORDER_STATUS_INVALID, LOCATION_INVALID, PRODUCT_EMPTY, PRODUCT_NOT_AVAILABLE, STRIPE_USER_CREATE_FAIL,
    USER_ID_NOT_PROVIDED, STRIPE_USER_NOT_FOUND, PRODUCT_PRICE_CHANGE_ERROR, TOKEN_NOT_VALID, USER_PHISHING, PAYMENT_PARAMS_INVALID

}
